image: cypress/base:12.12.0

variables:
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"
  CYPRESS_SCREENSHOTS_FOLDER: "$CI_PROJECT_DIR/artifacts/screenshots"
  CYPRESS_VIDEOS_FOLDER: "$CI_PROJECT_DIR/artifacts/videos"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - "node_modules/"
    - "$CYPRESS_CACHE_FOLDER"

stages:
  - test

test:
  stage: test
  script:
    - npm install
    - $(npm bin)/cypress run --spec "C:/Users/Karin/OneDrive/Área de Trabalho/SB/smart-ir/cypress/e2e/smartIr/smartt-IR.cy.js"
  artifacts:
    paths:
      - "$CYPRESS_SCREENSHOTS_FOLDER"
      - "$CYPRESS_VIDEOS_FOLDER"
